language: python
python: 3.7
before_install:
  # - set +x
  - echo -e $TRAVIS-AUTO-SYNC > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  # - set -x
  - git clone git@gitlab.com:ibm/skills-network/courses/IBMDeveloperSkillsNetwork-DS0201EN-SkillsNetwork.git testclone
script:
  - pip install flake8
  - pip install -r flaskapp/requirements.txt
  - flake8 flaskapp/telcochurn.py --ignore=E501 --ignore=F541
cache:
  directories:
    - $HOME/.cache/pip