# matrix:
#   include:
#     - language: node_js
#       node_js: 10
#       script:
#         - npm install markdownlint-cli
#         - markdownlint --config .markdownlint.json --ignore workshop/SUMMARY.md --ignore workshop/README.md workshop
---
- language: python
  python: 3.7
  script:
    - pip install flake8
    - pip install -r flaskapp/requirements.txt
    - flake8 flaskapp/telcochurn.py --ignore=E501 --ignore=F541
