language: python
python: 3.7
addons:
  ssh_known_hosts:
  - gitlab.com
  apt:
    packages:
    - sshpass
before_install:
- openssl aes-256-cbc -K $encrypted_ea20ea420691_key -iv $encrypted_ea20ea420691_iv
  -in sknet_deploy_key.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval `ssh-agent -s`
- sshpass -p $DEPLOY_KEYPHRASE ssh-add ~/.ssh/id_rsa
script:
- pip install flake8
# - pip install -r flaskapp/requirements.txt
# - flake8 flaskapp/telcochurn.py --ignore=E501 --ignore=F541
deploy:
  on:
    branch: 
      - skillsnetwork-course-master
      - adding-travis-to-sknet
  provider: script
  script: ./deploy/deploy.sh
cache:
  directories:
  - "$HOME/.cache/pip"
